import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef, SyntheticEvent, useState } from 'react'
import axios, { Axios } from 'axios';
const AddShift: NextPage = () => {
    const formRef = useRef<HTMLFormElement>(null)
    const [dayshift, setDayShift] = useState(new Date());
    const [currentDate, setNewDate] = useState(new Date());
    return (
        <div>
            <Head>
                <title>Add shift</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <form
                    ref={formRef}
                    onSubmit={async (e: SyntheticEvent) => {
                        e.preventDefault();
                        const target = e.target as typeof e.target & {
                            day: { value: string };
                        };
                        const day = Date.now(); // typechecks!
                        console.log(day)
                        const request = new Axios({
                            headers: {
                                'Content-Type': 'application/json',
                            }
                        })
                        // try {
                        // await request.post('/api/add-day-shift', JSON.stringify({ day: '2017-05-30T05:00:00.000Z' }))
                        // await request.post('/api/add-shift', JSON.stringify(
                        //     {
                        //         day: '2017-05-30T05:00:00.000Z',
                        //         starthour: '4:20:30',
                        //         endhour: '5:21:30',
                        //         title: 'third shift'
                        // }))
                        // await request.post('/api/get-shift', JSON.stringify(
                        //     {
                        //         day: '2017-05-29',
                        //     }))
                        await request.post('/api/get-day', JSON.stringify(
                            {
                                day: '2017-05-29',
                            }))
                        // } catch (e) {

                        // }
                        // etc...
                    }}
                >
                    <div>
                        <label>
                            Shift:
                            <input type="text" name="email" />
                        </label>
                    </div>
                    <div>
                        <input type="submit" value="Log in" />
                    </div>

                </form>
            </main>
        </div>
    )
}

export default AddShift
