import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef, SyntheticEvent, useState, SetStateAction } from 'react'
import SemanticDatepicker from 'react-semantic-ui-datepickers';
import 'react-semantic-ui-datepickers/dist/react-semantic-ui-datepickers.css';
import axios, { Axios } from 'axios';
const DayShift: NextPage = () => {
    const formRef = useRef<HTMLFormElement>(null)
    const [dayshift, setDayShift] = useState()
    const [currentDate, setNewDate] = useState(new Date());
    const onChange = (event: any, data: { value: SetStateAction<null>; }) => {
        setNewDate(data.value)
    };
    return (
        <div>
            <Head>
                <title>Add  Day shift</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <SemanticDatepicker value={currentDate} onChange={(elm, data) => onChange(elm, data)} />
            </main>
        </div>
    )
}

export default DayShift
